// Autogenerated from Pigeon (v12.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_EBS_PLUGIN_G_H_
#define PIGEON_EBS_PLUGIN_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>



// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class NativeHostApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


// Generated class from Pigeon that represents data sent in messages.
class EbsResult {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit EbsResult(
    bool success,
    const std::string& message);

  // Constructs an object setting all fields.
  explicit EbsResult(
    bool success,
    const std::string& message,
    const std::string* data);

  bool success() const;
  void set_success(bool value_arg);

  const std::string& message() const;
  void set_message(std::string_view value_arg);

  const std::string* data() const;
  void set_data(const std::string_view* value_arg);
  void set_data(std::string_view value_arg);


 private:
  static EbsResult FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class NativeHostApi;
  friend class NativeHostApiCodecSerializer;
  bool success_;
  std::string message_;
  std::optional<std::string> data_;

};

class NativeHostApiCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  NativeHostApiCodecSerializer();
  inline static NativeHostApiCodecSerializer& GetInstance() {
    static NativeHostApiCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;

 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;

};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class NativeHostApi {
 public:
  NativeHostApi(const NativeHostApi&) = delete;
  NativeHostApi& operator=(const NativeHostApi&) = delete;
  virtual ~NativeHostApi() {}
  virtual void InitializeEbsAdapter(
    const std::string& config,
    std::function<void(ErrorOr<EbsResult> reply)> result) = 0;
  virtual void AuthenticateUser(
    const std::string& username,
    const std::string& password,
    std::function<void(ErrorOr<EbsResult> reply)> result) = 0;
  virtual void VerifyCertificate(
    const std::string& certificate_data,
    std::function<void(ErrorOr<EbsResult> reply)> result) = 0;
  virtual void SignDocument(
    const std::string& document_data,
    std::function<void(ErrorOr<EbsResult> reply)> result) = 0;
  virtual void GetCertificateInfo(
    const std::string& certificate_data,
    std::function<void(ErrorOr<EbsResult> reply)> result) = 0;
  virtual void EncryptData(
    const std::string& data,
    const std::string& public_key,
    std::function<void(ErrorOr<EbsResult> reply)> result) = 0;
  virtual void DecryptData(
    const std::string& encrypted_data,
    const std::string& private_key,
    std::function<void(ErrorOr<EbsResult> reply)> result) = 0;
  virtual void ValidateDocument(
    const std::string& document_data,
    std::function<void(ErrorOr<EbsResult> reply)> result) = 0;
  virtual void SendDocument(
    const std::string& document_data,
    const std::string& recipient,
    std::function<void(ErrorOr<EbsResult> reply)> result) = 0;
  virtual void GetDocumentStatus(
    const std::string& document_id,
    std::function<void(ErrorOr<EbsResult> reply)> result) = 0;

  // The codec used by NativeHostApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `NativeHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    NativeHostApi* api);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);

 protected:
  NativeHostApi() = default;

};
#endif  // PIGEON_EBS_PLUGIN_G_H_
