// Autogenerated from Pigeon (v12.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class EbsResult;

@interface EbsResult : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithSuccess:(NSNumber *)success
    message:(NSString *)message
    data:(nullable NSString *)data;
@property(nonatomic, strong) NSNumber * success;
@property(nonatomic, copy) NSString * message;
@property(nonatomic, copy, nullable) NSString * data;
@end

/// The codec used by NativeHostApi.
NSObject<FlutterMessageCodec> *NativeHostApiGetCodec(void);

@protocol NativeHostApi
- (void)initializeEbsAdapterConfig:(NSString *)config completion:(void (^)(EbsResult *_Nullable, FlutterError *_Nullable))completion;
- (void)authenticateUserUsername:(NSString *)username password:(NSString *)password completion:(void (^)(EbsResult *_Nullable, FlutterError *_Nullable))completion;
- (void)verifyCertificateCertificateData:(NSString *)certificateData completion:(void (^)(EbsResult *_Nullable, FlutterError *_Nullable))completion;
- (void)signDocumentDocumentData:(NSString *)documentData completion:(void (^)(EbsResult *_Nullable, FlutterError *_Nullable))completion;
- (void)getCertificateInfoCertificateData:(NSString *)certificateData completion:(void (^)(EbsResult *_Nullable, FlutterError *_Nullable))completion;
- (void)encryptDataData:(NSString *)data publicKey:(NSString *)publicKey completion:(void (^)(EbsResult *_Nullable, FlutterError *_Nullable))completion;
- (void)decryptDataEncryptedData:(NSString *)encryptedData privateKey:(NSString *)privateKey completion:(void (^)(EbsResult *_Nullable, FlutterError *_Nullable))completion;
- (void)validateDocumentDocumentData:(NSString *)documentData completion:(void (^)(EbsResult *_Nullable, FlutterError *_Nullable))completion;
- (void)sendDocumentDocumentData:(NSString *)documentData recipient:(NSString *)recipient completion:(void (^)(EbsResult *_Nullable, FlutterError *_Nullable))completion;
- (void)getDocumentStatusDocumentId:(NSString *)documentId completion:(void (^)(EbsResult *_Nullable, FlutterError *_Nullable))completion;
@end

extern void SetUpNativeHostApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<NativeHostApi> *_Nullable api);

NS_ASSUME_NONNULL_END
